update 1.0.7

diff --git a/.github/workflows/backend-actions.yml b/.github/workflows/backend-actions.yml
--- a/.github/workflows/backend-actions.yml
+++ b/.github/workflows/backend-actions.yml
@@ -28,11 +28,20 @@ jobs:
         working-directory: ./back
         run: mvn clean package
 
-      - name: Test Report
-        uses: phoenix-actions/test-reporting@v8
-        id: test-report               # Set ID reference for step
-        if: success() || failure()    # run this step even if previous step failed
+      - name: 'Generate Jacoco report'
+        run: mvn jacoco:report
+
+      - name: 'Upload Jacoco coverage report'
+        uses: actions/upload-artifact@v2
         with:
-          name: JEST Tests            # Name of the check run which will be created
-          path: ./back/reports/jest-*.xml    # Path to test results
-          reporter: jest-junit        # Format of test results
+          name: jacoco-report
+          path: target/site/jacoco/index.html
+
+#      - name: Test Report
+#        uses: phoenix-actions/test-reporting@v8
+#        id: test-report               # Set ID reference for step
+#        if: success() || failure()    # run this step even if previous step failed
+#        with:
+#          name: JEST Tests            # Name of the check run which will be created
+#          path: ./back/reports/jest-*.xml    # Path to test results
+#          reporter: jest-junit        # Format of test results
